### PR TITLE
Added web application setup

### PR DESCRIPTION
**Pull request by manuelkoso**
Now it seems to work even as web app. We don't need a second repository (I excluded some Java classes from gwt compile).

### CODE REVIEW

**Comment by manuelkoso** [comment]
I don't understand why it doesn't pass the cli tests. On my computer it seems good, I can also start the web server and actually run the web app

**Comment by peiva-git** [comment]
I think the circleci build fails because there's a Gradle version mismatch. In the [new repository](https://github.com/peiva-git/SDM_project_GUI) I solved this issue, you basically need to change two lines in the config.yml file

**Comment by peiva-git** [comment]
I still think having a new repository for the GUI version is a better idea, to keep the two versions separate

**Comment by peiva-git** [comment]
Another solution to make the circleci build work, based on the error messages that I've seen, might be to revert the `build.gradle` file to revision `e9574b2ccf78d8a91f9247fe3e4e24fc551dd296`. In particular, I think the errors may be related to the `task beforeRun`, `task superDev` etc. lines, which should be reverted back to `tasks.register('beforeRun', ...)`

**Comment by manuelkoso** [comment]
> I still think having a new repository for the GUI version is a better idea, to keep the two versions separate

I don't think so, we will discuss later on the meeting

**Comment by peiva-git** [comment]
Great idea to put the terminal version in a separate module on the same repository, I'll just do some minor refactoring and then merge #65

**Review by peiva-git — APPROVED** [review]
Well done!

**Pull request merged**
