### PR TITLE
Implemented single boardSize field

### PR DESCRIPTION
**Pull request by peiva-git**
Closing #167. Also, corrected likely cause of the web release build failure

### CODE REVIEW

**Review by manuelkoso — CHANGES_REQUESTED** [review]
I would remove the method `isBoardSizeValid`.

**Comment by peiva-git** [comment]
But then we would need to duplicate the code for each implementation.

**Comment by peiva-git** [comment]
It could be refactored however, since we're allowing only square `Board`s. If we want to get rid of the limited `Board` size, we need to rethink the `Position` representation, which I would leave as a future improvement tho

**Comment by manuelkoso** [comment]
Ok, but then consider as method argument only `boardSize`, instead of two argument for columuns and rows

**Comment by manuelkoso** [comment]
Now, we can merge this branch

**Review by manuelkoso — APPROVED** [review]

**Pull request merged**
