### PR TITLE
Added documentation

### PR DESCRIPTION
**Pull request by peiva-git**

### CODE REVIEW

**Review by manuelkoso — COMMENTED** [review]
Well done! There are still some descriptions to add: classes/interface descriptions (`Board`, `Position`, `Stone` and so on) and public fields descriptions. I also noticed that for some methods even if you wrote the description, the `javadoc` doesn't put it in the output html page (see below). I used Intellij to create the doc page. 

error_doc

**Comment by peiva-git** [comment]
The `getPositions()` documentation is now being displayed correctly. I'll add descriptions for classes and public fields as well.

**Comment by manuelkoso** [comment]
I can do it as well if you want.

**Comment by peiva-git** [comment]
Ok, let me finish the part that I already started and then you can go on

**Comment by manuelkoso** [comment]
Some descriptions can be improved. Still missing the `terminal` module, I will do it. Just one note: the documentation of  all the libgdx overridden methods is misssing.

**Comment by peiva-git** [comment]
Done with reviewing. Minor changes were made. See #117.

**Comment by peiva-git** [comment]
This pull request can now be merged

**Review by manuelkoso — APPROVED** [review]
Well done

**Pull request merged**
