### PR TITLE
Added `FreedomBoardStatusObserver` to the `terminal` module

### PR DESCRIPTION
**Pull request by peiva-git**
Closing #109. Implemented `nextMove()` method

### CODE REVIEW

**Comment by manuelkoso** [comment]
Very nice! At the moment, I'm doing some small refactoring, but good job!

**Comment by manuelkoso** [comment]
As I told you, I did some refactoring. Let me know what you think about it.

**Review by manuelkoso — APPROVED** [review]
Check my refactoring. If you are okay with my changes you can merge this branch.

**Comment by peiva-git** [comment]
Refactoring looks good, I just improved stream usage in the `displayValidPositions()` method. I'll merge the request now

**Pull request merged**
