### PR TITLE
BoardAnalyzer class

### PR DESCRIPTION
**Pull request by manuelkoso**
Implementation of a BoardAnalyzer class, I also did some refactoring. It is still a working progress.

### CODE REVIEW

**Comment by peiva-git** [comment]
Seems to me like the BoardAnalyzer class is unnecessary, those methods belong to the Board class

**Comment by manuelkoso** [comment]
Maybe it is better, rather than use a Cell class, to have in the Board class the field `Map<Position, CellStatus> boardCells` where the CellStatus is an enum with the following values:
- FREE
- WHITE_STONE
- BLACK_STONE

Note: CellStatus was the first name that I came up

**Comment by peiva-git** [comment]
It would be perhaps simpler but less general

**Comment by manuelkoso** [comment]
Yes , you are right, but I think that we have to improve the general design. I still don't know how

**Pull request closed without merging**
